### ISSUE TITLE
Network Topology

### ISSUE THREAD

**Issue by brendyFlannel** [CSEC380-Group-12/CSEC380-Final-Project#19]
Generate a network topology for the application.

**Comment by Z5T1** [comment]
Reading through the project document. It looks like we are required to have (at a minimum) the following three Docker containers:

- Apache (or Nginx in our case) web server with a ‘Hello World’ index page (unit test for activity 2)
- Database (MySQL or MariaDB)
- Web frontend

Additionally, there are several unit tests we are required to have. Is this something Travis can handle on its own or should we maybe have a separate container for the unit tests?

I will start drafting a topology with those three containers and the physical host for Monday.
