### ISSUE TITLE
Log In

### ISSUE THREAD

**Issue by Z5T1** [CSEC380-Group-12/CSEC380-Final-Project#23]
As an end user, I want to be able to log in to the site so that I can upload videos.

Acceptance Criteria:
- Come up with a page that prompts a user for a username and password combination.
- On submission the page will check in a database if that username and password are correct. If successful the user should be redirected to a protected landing page.
- The landing page should not be accessible if a user has not authenticated.
- If the user enters the wrong information, he should be prompted that his information is incorrect.
- Information regarding account information should be stored in a MySQL/MariaDB instance.
- Generate a test case to demonstrate the ability to log in successfully.
- Generate a test case demonstrating that log in fails with an incorrect username.
- Generate a test case demonstrating that log in fails with an incorrect password.

**Comment by Bad3r** [comment]
Done
