### ISSUE TITLE
Upload Videos

### ISSUE THREAD

**Issue by Z5T1** [CSEC380-Group-12/CSEC380-Final-Project#26]
As a logged in user, I want to be able to upload new videos.

Acceptance Criteria:
- Uploads can be done by supplying a URL to an online movie (which will be downloaded by your code), or by uploading a movie file directly.
- Videos should be stored on the server with metadata stored in the Database.
- Generate a test case to verify this functionality.

**Comment by Bad3r** [comment]
Done
